// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: recognition_data_face.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from recognition_data_face.proto</summary>
public static partial class RecognitionDataFaceReflection {

  #region Descriptor
  /// <summary>File descriptor for recognition_data_face.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RecognitionDataFaceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtyZWNvZ25pdGlvbl9kYXRhX2ZhY2UucHJvdG8itAEKD1JlY29nbml0aW9u",
          "RGF0YRIwCgVmYWNlcxgBIAMoCzIhLk5vcm1hbGl6ZWRMYW5kbWFya0xpc3RD",
          "b2xsZWN0aW9uEhUKDWF1Z21lbnRhdGlvbnMYAiADKAkSEQoJdGltZXN0YW1w",
          "GAUgASgEEhsKE2NvbnRvdXJfdGhpY2tuZXNzZXMYBiADKAUSKAoPZmFjZU1l",
          "c2hfY29sb3JzGAcgAygLMg8uRmFjZU1lc2hDb2xvcnMiogEKEk5vcm1hbGl6",
          "ZWRMYW5kbWFyaxIOCgF4GAEgASgCSACIAQESDgoBeRgCIAEoAkgBiAEBEg4K",
          "AXoYAyABKAJIAogBARIXCgp2aXNpYmlsaXR5GAQgASgCSAOIAQESFQoIcHJl",
          "c2VuY2UYBSABKAJIBIgBAUIECgJfeEIECgJfeUIECgJfekINCgtfdmlzaWJp",
          "bGl0eUILCglfcHJlc2VuY2UiPwoWTm9ybWFsaXplZExhbmRtYXJrTGlzdBIl",
          "CghsYW5kbWFyaxgBIAMoCzITLk5vcm1hbGl6ZWRMYW5kbWFyayJSCiBOb3Jt",
          "YWxpemVkTGFuZG1hcmtMaXN0Q29sbGVjdGlvbhIuCg1sYW5kbWFya19saXN0",
          "GAEgAygLMhcuTm9ybWFsaXplZExhbmRtYXJrTGlzdCKDAwoORmFjZU1lc2hD",
          "b2xvcnMSLwobZmFjZU1lc2hfdGVzc2VsYXRpb25fY29sb3JzGAEgAygLMgou",
          "RWRnZUNvbG9yEisKF2ZhY2VNZXNoX2NvbnRvdXJfY29sb3JzGAIgAygLMgou",
          "RWRnZUNvbG9yEi0KGWZhY2VNZXNoX3JpZ2h0QnJvd19jb2xvcnMYAyADKAsy",
          "Ci5FZGdlQ29sb3ISLAoYZmFjZU1lc2hfbGVmdEJyb3dfY29sb3JzGAQgAygL",
          "MgouRWRnZUNvbG9yEiwKGGZhY2VNZXNoX3JpZ2h0RXllX2NvbG9ycxgFIAMo",
          "CzIKLkVkZ2VDb2xvchIrChdmYWNlTWVzaF9sZWZ0RXllX2NvbG9ycxgGIAMo",
          "CzIKLkVkZ2VDb2xvchItChlmYWNlTWVzaF9yaWdodElyaXNfY29sb3JzGAcg",
          "AygLMgouRWRnZUNvbG9yEiwKGGZhY2VNZXNoX2xlZnRJcmlzX2NvbG9ycxgI",
          "IAMoCzIKLkVkZ2VDb2xvciI3CglFZGdlQ29sb3ISCQoBchgBIAEoBRIJCgFn",
          "GAIgASgFEgkKAWIYAyABKAUSCQoBYRgEIAEoBWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RecognitionData), global::RecognitionData.Parser, new[]{ "Faces", "Augmentations", "Timestamp", "ContourThicknesses", "FaceMeshColors" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NormalizedLandmark), global::NormalizedLandmark.Parser, new[]{ "X", "Y", "Z", "Visibility", "Presence" }, new[]{ "X", "Y", "Z", "Visibility", "Presence" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NormalizedLandmarkList), global::NormalizedLandmarkList.Parser, new[]{ "Landmark" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NormalizedLandmarkListCollection), global::NormalizedLandmarkListCollection.Parser, new[]{ "LandmarkList" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FaceMeshColors), global::FaceMeshColors.Parser, new[]{ "FaceMeshTesselationColors", "FaceMeshContourColors", "FaceMeshRightBrowColors", "FaceMeshLeftBrowColors", "FaceMeshRightEyeColors", "FaceMeshLeftEyeColors", "FaceMeshRightIrisColors", "FaceMeshLeftIrisColors" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EdgeColor), global::EdgeColor.Parser, new[]{ "R", "G", "B", "A" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// TODO: Maybe add blendshapes later
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RecognitionData : pb::IMessage<RecognitionData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RecognitionData> _parser = new pb::MessageParser<RecognitionData>(() => new RecognitionData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RecognitionData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RecognitionData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RecognitionData(RecognitionData other) : this() {
    faces_ = other.faces_.Clone();
    augmentations_ = other.augmentations_.Clone();
    timestamp_ = other.timestamp_;
    contourThicknesses_ = other.contourThicknesses_.Clone();
    faceMeshColors_ = other.faceMeshColors_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RecognitionData Clone() {
    return new RecognitionData(this);
  }

  /// <summary>Field number for the "faces" field.</summary>
  public const int FacesFieldNumber = 1;
  private static readonly pb::FieldCodec<global::NormalizedLandmarkListCollection> _repeated_faces_codec
      = pb::FieldCodec.ForMessage(10, global::NormalizedLandmarkListCollection.Parser);
  private readonly pbc::RepeatedField<global::NormalizedLandmarkListCollection> faces_ = new pbc::RepeatedField<global::NormalizedLandmarkListCollection>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::NormalizedLandmarkListCollection> Faces {
    get { return faces_; }
  }

  /// <summary>Field number for the "augmentations" field.</summary>
  public const int AugmentationsFieldNumber = 2;
  private static readonly pb::FieldCodec<string> _repeated_augmentations_codec
      = pb::FieldCodec.ForString(18);
  private readonly pbc::RepeatedField<string> augmentations_ = new pbc::RepeatedField<string>();
  /// <summary>
  /// Here for if we have multiple face grid augmentations
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> Augmentations {
    get { return augmentations_; }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 5;
  private ulong timestamp_;
  /// <summary>
  /// Vec3 camera_position = 3;
  /// Vec3 camera_rotation = 4;
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  /// <summary>Field number for the "contour_thicknesses" field.</summary>
  public const int ContourThicknessesFieldNumber = 6;
  private static readonly pb::FieldCodec<int> _repeated_contourThicknesses_codec
      = pb::FieldCodec.ForInt32(50);
  private readonly pbc::RepeatedField<int> contourThicknesses_ = new pbc::RepeatedField<int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> ContourThicknesses {
    get { return contourThicknesses_; }
  }

  /// <summary>Field number for the "faceMesh_colors" field.</summary>
  public const int FaceMeshColorsFieldNumber = 7;
  private static readonly pb::FieldCodec<global::FaceMeshColors> _repeated_faceMeshColors_codec
      = pb::FieldCodec.ForMessage(58, global::FaceMeshColors.Parser);
  private readonly pbc::RepeatedField<global::FaceMeshColors> faceMeshColors_ = new pbc::RepeatedField<global::FaceMeshColors>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::FaceMeshColors> FaceMeshColors {
    get { return faceMeshColors_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RecognitionData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RecognitionData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!faces_.Equals(other.faces_)) return false;
    if(!augmentations_.Equals(other.augmentations_)) return false;
    if (Timestamp != other.Timestamp) return false;
    if(!contourThicknesses_.Equals(other.contourThicknesses_)) return false;
    if(!faceMeshColors_.Equals(other.faceMeshColors_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= faces_.GetHashCode();
    hash ^= augmentations_.GetHashCode();
    if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
    hash ^= contourThicknesses_.GetHashCode();
    hash ^= faceMeshColors_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    faces_.WriteTo(output, _repeated_faces_codec);
    augmentations_.WriteTo(output, _repeated_augmentations_codec);
    if (Timestamp != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(Timestamp);
    }
    contourThicknesses_.WriteTo(output, _repeated_contourThicknesses_codec);
    faceMeshColors_.WriteTo(output, _repeated_faceMeshColors_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    faces_.WriteTo(ref output, _repeated_faces_codec);
    augmentations_.WriteTo(ref output, _repeated_augmentations_codec);
    if (Timestamp != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(Timestamp);
    }
    contourThicknesses_.WriteTo(ref output, _repeated_contourThicknesses_codec);
    faceMeshColors_.WriteTo(ref output, _repeated_faceMeshColors_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += faces_.CalculateSize(_repeated_faces_codec);
    size += augmentations_.CalculateSize(_repeated_augmentations_codec);
    if (Timestamp != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
    }
    size += contourThicknesses_.CalculateSize(_repeated_contourThicknesses_codec);
    size += faceMeshColors_.CalculateSize(_repeated_faceMeshColors_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RecognitionData other) {
    if (other == null) {
      return;
    }
    faces_.Add(other.faces_);
    augmentations_.Add(other.augmentations_);
    if (other.Timestamp != 0UL) {
      Timestamp = other.Timestamp;
    }
    contourThicknesses_.Add(other.contourThicknesses_);
    faceMeshColors_.Add(other.faceMeshColors_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          faces_.AddEntriesFrom(input, _repeated_faces_codec);
          break;
        }
        case 18: {
          augmentations_.AddEntriesFrom(input, _repeated_augmentations_codec);
          break;
        }
        case 40: {
          Timestamp = input.ReadUInt64();
          break;
        }
        case 50:
        case 48: {
          contourThicknesses_.AddEntriesFrom(input, _repeated_contourThicknesses_codec);
          break;
        }
        case 58: {
          faceMeshColors_.AddEntriesFrom(input, _repeated_faceMeshColors_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          faces_.AddEntriesFrom(ref input, _repeated_faces_codec);
          break;
        }
        case 18: {
          augmentations_.AddEntriesFrom(ref input, _repeated_augmentations_codec);
          break;
        }
        case 40: {
          Timestamp = input.ReadUInt64();
          break;
        }
        case 50:
        case 48: {
          contourThicknesses_.AddEntriesFrom(ref input, _repeated_contourThicknesses_codec);
          break;
        }
        case 58: {
          faceMeshColors_.AddEntriesFrom(ref input, _repeated_faceMeshColors_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// A normalized version of above Landmark proto. All coordinates should be
/// within [0, 1].
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class NormalizedLandmark : pb::IMessage<NormalizedLandmark>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NormalizedLandmark> _parser = new pb::MessageParser<NormalizedLandmark>(() => new NormalizedLandmark());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NormalizedLandmark> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmark() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmark(NormalizedLandmark other) : this() {
    _hasBits0 = other._hasBits0;
    x_ = other.x_;
    y_ = other.y_;
    z_ = other.z_;
    visibility_ = other.visibility_;
    presence_ = other.presence_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmark Clone() {
    return new NormalizedLandmark(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private readonly static float XDefaultValue = 0F;

  private float x_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float X {
    get { if ((_hasBits0 & 1) != 0) { return x_; } else { return XDefaultValue; } }
    set {
      _hasBits0 |= 1;
      x_ = value;
    }
  }
  /// <summary>Gets whether the "x" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasX {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "x" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearX() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private readonly static float YDefaultValue = 0F;

  private float y_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Y {
    get { if ((_hasBits0 & 2) != 0) { return y_; } else { return YDefaultValue; } }
    set {
      _hasBits0 |= 2;
      y_ = value;
    }
  }
  /// <summary>Gets whether the "y" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasY {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "y" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearY() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "z" field.</summary>
  public const int ZFieldNumber = 3;
  private readonly static float ZDefaultValue = 0F;

  private float z_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Z {
    get { if ((_hasBits0 & 4) != 0) { return z_; } else { return ZDefaultValue; } }
    set {
      _hasBits0 |= 4;
      z_ = value;
    }
  }
  /// <summary>Gets whether the "z" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasZ {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "z" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearZ() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "visibility" field.</summary>
  public const int VisibilityFieldNumber = 4;
  private readonly static float VisibilityDefaultValue = 0F;

  private float visibility_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Visibility {
    get { if ((_hasBits0 & 8) != 0) { return visibility_; } else { return VisibilityDefaultValue; } }
    set {
      _hasBits0 |= 8;
      visibility_ = value;
    }
  }
  /// <summary>Gets whether the "visibility" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasVisibility {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "visibility" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearVisibility() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "presence" field.</summary>
  public const int PresenceFieldNumber = 5;
  private readonly static float PresenceDefaultValue = 0F;

  private float presence_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Presence {
    get { if ((_hasBits0 & 16) != 0) { return presence_; } else { return PresenceDefaultValue; } }
    set {
      _hasBits0 |= 16;
      presence_ = value;
    }
  }
  /// <summary>Gets whether the "presence" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPresence {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "presence" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPresence() {
    _hasBits0 &= ~16;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NormalizedLandmark);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NormalizedLandmark other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Visibility, other.Visibility)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Presence, other.Presence)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasX) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
    if (HasY) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
    if (HasZ) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
    if (HasVisibility) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Visibility);
    if (HasPresence) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Presence);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasX) {
      output.WriteRawTag(13);
      output.WriteFloat(X);
    }
    if (HasY) {
      output.WriteRawTag(21);
      output.WriteFloat(Y);
    }
    if (HasZ) {
      output.WriteRawTag(29);
      output.WriteFloat(Z);
    }
    if (HasVisibility) {
      output.WriteRawTag(37);
      output.WriteFloat(Visibility);
    }
    if (HasPresence) {
      output.WriteRawTag(45);
      output.WriteFloat(Presence);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasX) {
      output.WriteRawTag(13);
      output.WriteFloat(X);
    }
    if (HasY) {
      output.WriteRawTag(21);
      output.WriteFloat(Y);
    }
    if (HasZ) {
      output.WriteRawTag(29);
      output.WriteFloat(Z);
    }
    if (HasVisibility) {
      output.WriteRawTag(37);
      output.WriteFloat(Visibility);
    }
    if (HasPresence) {
      output.WriteRawTag(45);
      output.WriteFloat(Presence);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasX) {
      size += 1 + 4;
    }
    if (HasY) {
      size += 1 + 4;
    }
    if (HasZ) {
      size += 1 + 4;
    }
    if (HasVisibility) {
      size += 1 + 4;
    }
    if (HasPresence) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NormalizedLandmark other) {
    if (other == null) {
      return;
    }
    if (other.HasX) {
      X = other.X;
    }
    if (other.HasY) {
      Y = other.Y;
    }
    if (other.HasZ) {
      Z = other.Z;
    }
    if (other.HasVisibility) {
      Visibility = other.Visibility;
    }
    if (other.HasPresence) {
      Presence = other.Presence;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          X = input.ReadFloat();
          break;
        }
        case 21: {
          Y = input.ReadFloat();
          break;
        }
        case 29: {
          Z = input.ReadFloat();
          break;
        }
        case 37: {
          Visibility = input.ReadFloat();
          break;
        }
        case 45: {
          Presence = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 13: {
          X = input.ReadFloat();
          break;
        }
        case 21: {
          Y = input.ReadFloat();
          break;
        }
        case 29: {
          Z = input.ReadFloat();
          break;
        }
        case 37: {
          Visibility = input.ReadFloat();
          break;
        }
        case 45: {
          Presence = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Group of NormalizedLandmark protos.
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class NormalizedLandmarkList : pb::IMessage<NormalizedLandmarkList>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NormalizedLandmarkList> _parser = new pb::MessageParser<NormalizedLandmarkList>(() => new NormalizedLandmarkList());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NormalizedLandmarkList> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkList() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkList(NormalizedLandmarkList other) : this() {
    landmark_ = other.landmark_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkList Clone() {
    return new NormalizedLandmarkList(this);
  }

  /// <summary>Field number for the "landmark" field.</summary>
  public const int LandmarkFieldNumber = 1;
  private static readonly pb::FieldCodec<global::NormalizedLandmark> _repeated_landmark_codec
      = pb::FieldCodec.ForMessage(10, global::NormalizedLandmark.Parser);
  private readonly pbc::RepeatedField<global::NormalizedLandmark> landmark_ = new pbc::RepeatedField<global::NormalizedLandmark>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::NormalizedLandmark> Landmark {
    get { return landmark_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NormalizedLandmarkList);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NormalizedLandmarkList other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!landmark_.Equals(other.landmark_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= landmark_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    landmark_.WriteTo(output, _repeated_landmark_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    landmark_.WriteTo(ref output, _repeated_landmark_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += landmark_.CalculateSize(_repeated_landmark_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NormalizedLandmarkList other) {
    if (other == null) {
      return;
    }
    landmark_.Add(other.landmark_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          landmark_.AddEntriesFrom(input, _repeated_landmark_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          landmark_.AddEntriesFrom(ref input, _repeated_landmark_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Group of NormalizedLandmarkList protos.
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class NormalizedLandmarkListCollection : pb::IMessage<NormalizedLandmarkListCollection>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NormalizedLandmarkListCollection> _parser = new pb::MessageParser<NormalizedLandmarkListCollection>(() => new NormalizedLandmarkListCollection());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NormalizedLandmarkListCollection> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkListCollection() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkListCollection(NormalizedLandmarkListCollection other) : this() {
    landmarkList_ = other.landmarkList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkListCollection Clone() {
    return new NormalizedLandmarkListCollection(this);
  }

  /// <summary>Field number for the "landmark_list" field.</summary>
  public const int LandmarkListFieldNumber = 1;
  private static readonly pb::FieldCodec<global::NormalizedLandmarkList> _repeated_landmarkList_codec
      = pb::FieldCodec.ForMessage(10, global::NormalizedLandmarkList.Parser);
  private readonly pbc::RepeatedField<global::NormalizedLandmarkList> landmarkList_ = new pbc::RepeatedField<global::NormalizedLandmarkList>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::NormalizedLandmarkList> LandmarkList {
    get { return landmarkList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NormalizedLandmarkListCollection);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NormalizedLandmarkListCollection other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!landmarkList_.Equals(other.landmarkList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= landmarkList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    landmarkList_.WriteTo(output, _repeated_landmarkList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    landmarkList_.WriteTo(ref output, _repeated_landmarkList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += landmarkList_.CalculateSize(_repeated_landmarkList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NormalizedLandmarkListCollection other) {
    if (other == null) {
      return;
    }
    landmarkList_.Add(other.landmarkList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          landmarkList_.AddEntriesFrom(input, _repeated_landmarkList_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          landmarkList_.AddEntriesFrom(ref input, _repeated_landmarkList_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Could also add seperate color for lips?
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class FaceMeshColors : pb::IMessage<FaceMeshColors>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FaceMeshColors> _parser = new pb::MessageParser<FaceMeshColors>(() => new FaceMeshColors());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FaceMeshColors> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FaceMeshColors() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FaceMeshColors(FaceMeshColors other) : this() {
    faceMeshTesselationColors_ = other.faceMeshTesselationColors_.Clone();
    faceMeshContourColors_ = other.faceMeshContourColors_.Clone();
    faceMeshRightBrowColors_ = other.faceMeshRightBrowColors_.Clone();
    faceMeshLeftBrowColors_ = other.faceMeshLeftBrowColors_.Clone();
    faceMeshRightEyeColors_ = other.faceMeshRightEyeColors_.Clone();
    faceMeshLeftEyeColors_ = other.faceMeshLeftEyeColors_.Clone();
    faceMeshRightIrisColors_ = other.faceMeshRightIrisColors_.Clone();
    faceMeshLeftIrisColors_ = other.faceMeshLeftIrisColors_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FaceMeshColors Clone() {
    return new FaceMeshColors(this);
  }

  /// <summary>Field number for the "faceMesh_tesselation_colors" field.</summary>
  public const int FaceMeshTesselationColorsFieldNumber = 1;
  private static readonly pb::FieldCodec<global::EdgeColor> _repeated_faceMeshTesselationColors_codec
      = pb::FieldCodec.ForMessage(10, global::EdgeColor.Parser);
  private readonly pbc::RepeatedField<global::EdgeColor> faceMeshTesselationColors_ = new pbc::RepeatedField<global::EdgeColor>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EdgeColor> FaceMeshTesselationColors {
    get { return faceMeshTesselationColors_; }
  }

  /// <summary>Field number for the "faceMesh_contour_colors" field.</summary>
  public const int FaceMeshContourColorsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::EdgeColor> _repeated_faceMeshContourColors_codec
      = pb::FieldCodec.ForMessage(18, global::EdgeColor.Parser);
  private readonly pbc::RepeatedField<global::EdgeColor> faceMeshContourColors_ = new pbc::RepeatedField<global::EdgeColor>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EdgeColor> FaceMeshContourColors {
    get { return faceMeshContourColors_; }
  }

  /// <summary>Field number for the "faceMesh_rightBrow_colors" field.</summary>
  public const int FaceMeshRightBrowColorsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::EdgeColor> _repeated_faceMeshRightBrowColors_codec
      = pb::FieldCodec.ForMessage(26, global::EdgeColor.Parser);
  private readonly pbc::RepeatedField<global::EdgeColor> faceMeshRightBrowColors_ = new pbc::RepeatedField<global::EdgeColor>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EdgeColor> FaceMeshRightBrowColors {
    get { return faceMeshRightBrowColors_; }
  }

  /// <summary>Field number for the "faceMesh_leftBrow_colors" field.</summary>
  public const int FaceMeshLeftBrowColorsFieldNumber = 4;
  private static readonly pb::FieldCodec<global::EdgeColor> _repeated_faceMeshLeftBrowColors_codec
      = pb::FieldCodec.ForMessage(34, global::EdgeColor.Parser);
  private readonly pbc::RepeatedField<global::EdgeColor> faceMeshLeftBrowColors_ = new pbc::RepeatedField<global::EdgeColor>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EdgeColor> FaceMeshLeftBrowColors {
    get { return faceMeshLeftBrowColors_; }
  }

  /// <summary>Field number for the "faceMesh_rightEye_colors" field.</summary>
  public const int FaceMeshRightEyeColorsFieldNumber = 5;
  private static readonly pb::FieldCodec<global::EdgeColor> _repeated_faceMeshRightEyeColors_codec
      = pb::FieldCodec.ForMessage(42, global::EdgeColor.Parser);
  private readonly pbc::RepeatedField<global::EdgeColor> faceMeshRightEyeColors_ = new pbc::RepeatedField<global::EdgeColor>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EdgeColor> FaceMeshRightEyeColors {
    get { return faceMeshRightEyeColors_; }
  }

  /// <summary>Field number for the "faceMesh_leftEye_colors" field.</summary>
  public const int FaceMeshLeftEyeColorsFieldNumber = 6;
  private static readonly pb::FieldCodec<global::EdgeColor> _repeated_faceMeshLeftEyeColors_codec
      = pb::FieldCodec.ForMessage(50, global::EdgeColor.Parser);
  private readonly pbc::RepeatedField<global::EdgeColor> faceMeshLeftEyeColors_ = new pbc::RepeatedField<global::EdgeColor>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EdgeColor> FaceMeshLeftEyeColors {
    get { return faceMeshLeftEyeColors_; }
  }

  /// <summary>Field number for the "faceMesh_rightIris_colors" field.</summary>
  public const int FaceMeshRightIrisColorsFieldNumber = 7;
  private static readonly pb::FieldCodec<global::EdgeColor> _repeated_faceMeshRightIrisColors_codec
      = pb::FieldCodec.ForMessage(58, global::EdgeColor.Parser);
  private readonly pbc::RepeatedField<global::EdgeColor> faceMeshRightIrisColors_ = new pbc::RepeatedField<global::EdgeColor>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EdgeColor> FaceMeshRightIrisColors {
    get { return faceMeshRightIrisColors_; }
  }

  /// <summary>Field number for the "faceMesh_leftIris_colors" field.</summary>
  public const int FaceMeshLeftIrisColorsFieldNumber = 8;
  private static readonly pb::FieldCodec<global::EdgeColor> _repeated_faceMeshLeftIrisColors_codec
      = pb::FieldCodec.ForMessage(66, global::EdgeColor.Parser);
  private readonly pbc::RepeatedField<global::EdgeColor> faceMeshLeftIrisColors_ = new pbc::RepeatedField<global::EdgeColor>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EdgeColor> FaceMeshLeftIrisColors {
    get { return faceMeshLeftIrisColors_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FaceMeshColors);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FaceMeshColors other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!faceMeshTesselationColors_.Equals(other.faceMeshTesselationColors_)) return false;
    if(!faceMeshContourColors_.Equals(other.faceMeshContourColors_)) return false;
    if(!faceMeshRightBrowColors_.Equals(other.faceMeshRightBrowColors_)) return false;
    if(!faceMeshLeftBrowColors_.Equals(other.faceMeshLeftBrowColors_)) return false;
    if(!faceMeshRightEyeColors_.Equals(other.faceMeshRightEyeColors_)) return false;
    if(!faceMeshLeftEyeColors_.Equals(other.faceMeshLeftEyeColors_)) return false;
    if(!faceMeshRightIrisColors_.Equals(other.faceMeshRightIrisColors_)) return false;
    if(!faceMeshLeftIrisColors_.Equals(other.faceMeshLeftIrisColors_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= faceMeshTesselationColors_.GetHashCode();
    hash ^= faceMeshContourColors_.GetHashCode();
    hash ^= faceMeshRightBrowColors_.GetHashCode();
    hash ^= faceMeshLeftBrowColors_.GetHashCode();
    hash ^= faceMeshRightEyeColors_.GetHashCode();
    hash ^= faceMeshLeftEyeColors_.GetHashCode();
    hash ^= faceMeshRightIrisColors_.GetHashCode();
    hash ^= faceMeshLeftIrisColors_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    faceMeshTesselationColors_.WriteTo(output, _repeated_faceMeshTesselationColors_codec);
    faceMeshContourColors_.WriteTo(output, _repeated_faceMeshContourColors_codec);
    faceMeshRightBrowColors_.WriteTo(output, _repeated_faceMeshRightBrowColors_codec);
    faceMeshLeftBrowColors_.WriteTo(output, _repeated_faceMeshLeftBrowColors_codec);
    faceMeshRightEyeColors_.WriteTo(output, _repeated_faceMeshRightEyeColors_codec);
    faceMeshLeftEyeColors_.WriteTo(output, _repeated_faceMeshLeftEyeColors_codec);
    faceMeshRightIrisColors_.WriteTo(output, _repeated_faceMeshRightIrisColors_codec);
    faceMeshLeftIrisColors_.WriteTo(output, _repeated_faceMeshLeftIrisColors_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    faceMeshTesselationColors_.WriteTo(ref output, _repeated_faceMeshTesselationColors_codec);
    faceMeshContourColors_.WriteTo(ref output, _repeated_faceMeshContourColors_codec);
    faceMeshRightBrowColors_.WriteTo(ref output, _repeated_faceMeshRightBrowColors_codec);
    faceMeshLeftBrowColors_.WriteTo(ref output, _repeated_faceMeshLeftBrowColors_codec);
    faceMeshRightEyeColors_.WriteTo(ref output, _repeated_faceMeshRightEyeColors_codec);
    faceMeshLeftEyeColors_.WriteTo(ref output, _repeated_faceMeshLeftEyeColors_codec);
    faceMeshRightIrisColors_.WriteTo(ref output, _repeated_faceMeshRightIrisColors_codec);
    faceMeshLeftIrisColors_.WriteTo(ref output, _repeated_faceMeshLeftIrisColors_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += faceMeshTesselationColors_.CalculateSize(_repeated_faceMeshTesselationColors_codec);
    size += faceMeshContourColors_.CalculateSize(_repeated_faceMeshContourColors_codec);
    size += faceMeshRightBrowColors_.CalculateSize(_repeated_faceMeshRightBrowColors_codec);
    size += faceMeshLeftBrowColors_.CalculateSize(_repeated_faceMeshLeftBrowColors_codec);
    size += faceMeshRightEyeColors_.CalculateSize(_repeated_faceMeshRightEyeColors_codec);
    size += faceMeshLeftEyeColors_.CalculateSize(_repeated_faceMeshLeftEyeColors_codec);
    size += faceMeshRightIrisColors_.CalculateSize(_repeated_faceMeshRightIrisColors_codec);
    size += faceMeshLeftIrisColors_.CalculateSize(_repeated_faceMeshLeftIrisColors_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FaceMeshColors other) {
    if (other == null) {
      return;
    }
    faceMeshTesselationColors_.Add(other.faceMeshTesselationColors_);
    faceMeshContourColors_.Add(other.faceMeshContourColors_);
    faceMeshRightBrowColors_.Add(other.faceMeshRightBrowColors_);
    faceMeshLeftBrowColors_.Add(other.faceMeshLeftBrowColors_);
    faceMeshRightEyeColors_.Add(other.faceMeshRightEyeColors_);
    faceMeshLeftEyeColors_.Add(other.faceMeshLeftEyeColors_);
    faceMeshRightIrisColors_.Add(other.faceMeshRightIrisColors_);
    faceMeshLeftIrisColors_.Add(other.faceMeshLeftIrisColors_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          faceMeshTesselationColors_.AddEntriesFrom(input, _repeated_faceMeshTesselationColors_codec);
          break;
        }
        case 18: {
          faceMeshContourColors_.AddEntriesFrom(input, _repeated_faceMeshContourColors_codec);
          break;
        }
        case 26: {
          faceMeshRightBrowColors_.AddEntriesFrom(input, _repeated_faceMeshRightBrowColors_codec);
          break;
        }
        case 34: {
          faceMeshLeftBrowColors_.AddEntriesFrom(input, _repeated_faceMeshLeftBrowColors_codec);
          break;
        }
        case 42: {
          faceMeshRightEyeColors_.AddEntriesFrom(input, _repeated_faceMeshRightEyeColors_codec);
          break;
        }
        case 50: {
          faceMeshLeftEyeColors_.AddEntriesFrom(input, _repeated_faceMeshLeftEyeColors_codec);
          break;
        }
        case 58: {
          faceMeshRightIrisColors_.AddEntriesFrom(input, _repeated_faceMeshRightIrisColors_codec);
          break;
        }
        case 66: {
          faceMeshLeftIrisColors_.AddEntriesFrom(input, _repeated_faceMeshLeftIrisColors_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          faceMeshTesselationColors_.AddEntriesFrom(ref input, _repeated_faceMeshTesselationColors_codec);
          break;
        }
        case 18: {
          faceMeshContourColors_.AddEntriesFrom(ref input, _repeated_faceMeshContourColors_codec);
          break;
        }
        case 26: {
          faceMeshRightBrowColors_.AddEntriesFrom(ref input, _repeated_faceMeshRightBrowColors_codec);
          break;
        }
        case 34: {
          faceMeshLeftBrowColors_.AddEntriesFrom(ref input, _repeated_faceMeshLeftBrowColors_codec);
          break;
        }
        case 42: {
          faceMeshRightEyeColors_.AddEntriesFrom(ref input, _repeated_faceMeshRightEyeColors_codec);
          break;
        }
        case 50: {
          faceMeshLeftEyeColors_.AddEntriesFrom(ref input, _repeated_faceMeshLeftEyeColors_codec);
          break;
        }
        case 58: {
          faceMeshRightIrisColors_.AddEntriesFrom(ref input, _repeated_faceMeshRightIrisColors_codec);
          break;
        }
        case 66: {
          faceMeshLeftIrisColors_.AddEntriesFrom(ref input, _repeated_faceMeshLeftIrisColors_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// each color is a 4-tuple (r, g, b, a)
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EdgeColor : pb::IMessage<EdgeColor>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EdgeColor> _parser = new pb::MessageParser<EdgeColor>(() => new EdgeColor());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EdgeColor> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EdgeColor() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EdgeColor(EdgeColor other) : this() {
    r_ = other.r_;
    g_ = other.g_;
    b_ = other.b_;
    a_ = other.a_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EdgeColor Clone() {
    return new EdgeColor(this);
  }

  /// <summary>Field number for the "r" field.</summary>
  public const int RFieldNumber = 1;
  private int r_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int R {
    get { return r_; }
    set {
      r_ = value;
    }
  }

  /// <summary>Field number for the "g" field.</summary>
  public const int GFieldNumber = 2;
  private int g_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int G {
    get { return g_; }
    set {
      g_ = value;
    }
  }

  /// <summary>Field number for the "b" field.</summary>
  public const int BFieldNumber = 3;
  private int b_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int B {
    get { return b_; }
    set {
      b_ = value;
    }
  }

  /// <summary>Field number for the "a" field.</summary>
  public const int AFieldNumber = 4;
  private int a_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int A {
    get { return a_; }
    set {
      a_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EdgeColor);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EdgeColor other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (R != other.R) return false;
    if (G != other.G) return false;
    if (B != other.B) return false;
    if (A != other.A) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (R != 0) hash ^= R.GetHashCode();
    if (G != 0) hash ^= G.GetHashCode();
    if (B != 0) hash ^= B.GetHashCode();
    if (A != 0) hash ^= A.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (R != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(R);
    }
    if (G != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(G);
    }
    if (B != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(B);
    }
    if (A != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(A);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (R != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(R);
    }
    if (G != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(G);
    }
    if (B != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(B);
    }
    if (A != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(A);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (R != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(R);
    }
    if (G != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(G);
    }
    if (B != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(B);
    }
    if (A != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(A);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EdgeColor other) {
    if (other == null) {
      return;
    }
    if (other.R != 0) {
      R = other.R;
    }
    if (other.G != 0) {
      G = other.G;
    }
    if (other.B != 0) {
      B = other.B;
    }
    if (other.A != 0) {
      A = other.A;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          R = input.ReadInt32();
          break;
        }
        case 16: {
          G = input.ReadInt32();
          break;
        }
        case 24: {
          B = input.ReadInt32();
          break;
        }
        case 32: {
          A = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          R = input.ReadInt32();
          break;
        }
        case 16: {
          G = input.ReadInt32();
          break;
        }
        case 24: {
          B = input.ReadInt32();
          break;
        }
        case 32: {
          A = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
