// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: recognition_data_face.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from recognition_data_face.proto</summary>
public static partial class RecognitionDataFaceReflection {

  #region Descriptor
  /// <summary>File descriptor for recognition_data_face.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RecognitionDataFaceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtyZWNvZ25pdGlvbl9kYXRhX2ZhY2UucHJvdG8iyAEKD1JlY29nbml0aW9u",
          "RGF0YRIwCgVmYWNlcxgBIAMoCzIhLk5vcm1hbGl6ZWRMYW5kbWFya0xpc3RD",
          "b2xsZWN0aW9uEikKDWF1Z21lbnRhdGlvbnMYAiADKAsyEi5GYWNlQXVnbWVu",
          "dGF0aW9ucxIRCgl0aW1lc3RhbXAYBSABKAQSGwoTY29udG91cl90aGlja25l",
          "c3NlcxgGIAMoBRIoCg9mYWNlTWVzaF9jb2xvcnMYByADKAsyDy5GYWNlTWVz",
          "aENvbG9ycyKiAQoSTm9ybWFsaXplZExhbmRtYXJrEg4KAXgYASABKAJIAIgB",
          "ARIOCgF5GAIgASgCSAGIAQESDgoBehgDIAEoAkgCiAEBEhcKCnZpc2liaWxp",
          "dHkYBCABKAJIA4gBARIVCghwcmVzZW5jZRgFIAEoAkgEiAEBQgQKAl94QgQK",
          "Al95QgQKAl96Qg0KC192aXNpYmlsaXR5QgsKCV9wcmVzZW5jZSJAChZOb3Jt",
          "YWxpemVkTGFuZG1hcmtMaXN0EiYKCWxhbmRtYXJrcxgBIAMoCzITLk5vcm1h",
          "bGl6ZWRMYW5kbWFyayJTCiBOb3JtYWxpemVkTGFuZG1hcmtMaXN0Q29sbGVj",
          "dGlvbhIvCg5sYW5kbWFya19saXN0cxgBIAMoCzIXLk5vcm1hbGl6ZWRMYW5k",
          "bWFya0xpc3Qi+wIKDkZhY2VNZXNoQ29sb3JzEi4KGmZhY2VNZXNoX3Rlc3Nl",
          "bGF0aW9uX2NvbG9yGAEgASgLMgouRWRnZUNvbG9yEioKFmZhY2VNZXNoX2Nv",
          "bnRvdXJfY29sb3IYAiABKAsyCi5FZGdlQ29sb3ISLAoYZmFjZU1lc2hfcmln",
          "aHRCcm93X2NvbG9yGAMgASgLMgouRWRnZUNvbG9yEisKF2ZhY2VNZXNoX2xl",
          "ZnRCcm93X2NvbG9yGAQgASgLMgouRWRnZUNvbG9yEisKF2ZhY2VNZXNoX3Jp",
          "Z2h0RXllX2NvbG9yGAUgASgLMgouRWRnZUNvbG9yEioKFmZhY2VNZXNoX2xl",
          "ZnRFeWVfY29sb3IYBiABKAsyCi5FZGdlQ29sb3ISLAoYZmFjZU1lc2hfcmln",
          "aHRJcmlzX2NvbG9yGAcgASgLMgouRWRnZUNvbG9yEisKF2ZhY2VNZXNoX2xl",
          "ZnRJcmlzX2NvbG9yGAggASgLMgouRWRnZUNvbG9yIjcKCUVkZ2VDb2xvchIJ",
          "CgFyGAEgASgFEgkKAWcYAiABKAUSCQoBYhgDIAEoBRIJCgFhGAQgASgFIqYC",
          "ChFGYWNlQXVnbWVudGF0aW9ucxIjChtmYWNlTWVzaF90ZXNzZWxhdGlvbl9k",
          "ZXNpZ24YASABKAkSHwoXZmFjZU1lc2hfY29udG91cl9kZXNpZ24YAiABKAkS",
          "IQoZZmFjZU1lc2hfcmlnaHRCcm93X2Rlc2lnbhgDIAEoCRIgChhmYWNlTWVz",
          "aF9sZWZ0QnJvd19kZXNpZ24YBCABKAkSIAoYZmFjZU1lc2hfcmlnaHRFeWVf",
          "ZGVzaWduGAUgASgJEh8KF2ZhY2VNZXNoX2xlZnRFeWVfZGVzaWduGAYgASgJ",
          "EiEKGWZhY2VNZXNoX3JpZ2h0SXJpc19kZXNpZ24YByABKAkSIAoYZmFjZU1l",
          "c2hfbGVmdElyaXNfZGVzaWduGAggASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RecognitionData), global::RecognitionData.Parser, new[]{ "Faces", "Augmentations", "Timestamp", "ContourThicknesses", "FaceMeshColors" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NormalizedLandmark), global::NormalizedLandmark.Parser, new[]{ "X", "Y", "Z", "Visibility", "Presence" }, new[]{ "X", "Y", "Z", "Visibility", "Presence" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NormalizedLandmarkList), global::NormalizedLandmarkList.Parser, new[]{ "Landmarks" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NormalizedLandmarkListCollection), global::NormalizedLandmarkListCollection.Parser, new[]{ "LandmarkLists" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FaceMeshColors), global::FaceMeshColors.Parser, new[]{ "FaceMeshTesselationColor", "FaceMeshContourColor", "FaceMeshRightBrowColor", "FaceMeshLeftBrowColor", "FaceMeshRightEyeColor", "FaceMeshLeftEyeColor", "FaceMeshRightIrisColor", "FaceMeshLeftIrisColor" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EdgeColor), global::EdgeColor.Parser, new[]{ "R", "G", "B", "A" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FaceAugmentations), global::FaceAugmentations.Parser, new[]{ "FaceMeshTesselationDesign", "FaceMeshContourDesign", "FaceMeshRightBrowDesign", "FaceMeshLeftBrowDesign", "FaceMeshRightEyeDesign", "FaceMeshLeftEyeDesign", "FaceMeshRightIrisDesign", "FaceMeshLeftIrisDesign" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// TODO: Maybe add blendshapes later
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RecognitionData : pb::IMessage<RecognitionData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RecognitionData> _parser = new pb::MessageParser<RecognitionData>(() => new RecognitionData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RecognitionData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RecognitionData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RecognitionData(RecognitionData other) : this() {
    faces_ = other.faces_.Clone();
    augmentations_ = other.augmentations_.Clone();
    timestamp_ = other.timestamp_;
    contourThicknesses_ = other.contourThicknesses_.Clone();
    faceMeshColors_ = other.faceMeshColors_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RecognitionData Clone() {
    return new RecognitionData(this);
  }

  /// <summary>Field number for the "faces" field.</summary>
  public const int FacesFieldNumber = 1;
  private static readonly pb::FieldCodec<global::NormalizedLandmarkListCollection> _repeated_faces_codec
      = pb::FieldCodec.ForMessage(10, global::NormalizedLandmarkListCollection.Parser);
  private readonly pbc::RepeatedField<global::NormalizedLandmarkListCollection> faces_ = new pbc::RepeatedField<global::NormalizedLandmarkListCollection>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::NormalizedLandmarkListCollection> Faces {
    get { return faces_; }
  }

  /// <summary>Field number for the "augmentations" field.</summary>
  public const int AugmentationsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::FaceAugmentations> _repeated_augmentations_codec
      = pb::FieldCodec.ForMessage(18, global::FaceAugmentations.Parser);
  private readonly pbc::RepeatedField<global::FaceAugmentations> augmentations_ = new pbc::RepeatedField<global::FaceAugmentations>();
  /// <summary>
  /// Here for if we want different augmentations for diff faces
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::FaceAugmentations> Augmentations {
    get { return augmentations_; }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 5;
  private ulong timestamp_;
  /// <summary>
  /// Vec3 camera_position = 3;
  /// Vec3 camera_rotation = 4;
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  /// <summary>Field number for the "contour_thicknesses" field.</summary>
  public const int ContourThicknessesFieldNumber = 6;
  private static readonly pb::FieldCodec<int> _repeated_contourThicknesses_codec
      = pb::FieldCodec.ForInt32(50);
  private readonly pbc::RepeatedField<int> contourThicknesses_ = new pbc::RepeatedField<int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> ContourThicknesses {
    get { return contourThicknesses_; }
  }

  /// <summary>Field number for the "faceMesh_colors" field.</summary>
  public const int FaceMeshColorsFieldNumber = 7;
  private static readonly pb::FieldCodec<global::FaceMeshColors> _repeated_faceMeshColors_codec
      = pb::FieldCodec.ForMessage(58, global::FaceMeshColors.Parser);
  private readonly pbc::RepeatedField<global::FaceMeshColors> faceMeshColors_ = new pbc::RepeatedField<global::FaceMeshColors>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::FaceMeshColors> FaceMeshColors {
    get { return faceMeshColors_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RecognitionData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RecognitionData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!faces_.Equals(other.faces_)) return false;
    if(!augmentations_.Equals(other.augmentations_)) return false;
    if (Timestamp != other.Timestamp) return false;
    if(!contourThicknesses_.Equals(other.contourThicknesses_)) return false;
    if(!faceMeshColors_.Equals(other.faceMeshColors_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= faces_.GetHashCode();
    hash ^= augmentations_.GetHashCode();
    if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
    hash ^= contourThicknesses_.GetHashCode();
    hash ^= faceMeshColors_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    faces_.WriteTo(output, _repeated_faces_codec);
    augmentations_.WriteTo(output, _repeated_augmentations_codec);
    if (Timestamp != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(Timestamp);
    }
    contourThicknesses_.WriteTo(output, _repeated_contourThicknesses_codec);
    faceMeshColors_.WriteTo(output, _repeated_faceMeshColors_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    faces_.WriteTo(ref output, _repeated_faces_codec);
    augmentations_.WriteTo(ref output, _repeated_augmentations_codec);
    if (Timestamp != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(Timestamp);
    }
    contourThicknesses_.WriteTo(ref output, _repeated_contourThicknesses_codec);
    faceMeshColors_.WriteTo(ref output, _repeated_faceMeshColors_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += faces_.CalculateSize(_repeated_faces_codec);
    size += augmentations_.CalculateSize(_repeated_augmentations_codec);
    if (Timestamp != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
    }
    size += contourThicknesses_.CalculateSize(_repeated_contourThicknesses_codec);
    size += faceMeshColors_.CalculateSize(_repeated_faceMeshColors_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RecognitionData other) {
    if (other == null) {
      return;
    }
    faces_.Add(other.faces_);
    augmentations_.Add(other.augmentations_);
    if (other.Timestamp != 0UL) {
      Timestamp = other.Timestamp;
    }
    contourThicknesses_.Add(other.contourThicknesses_);
    faceMeshColors_.Add(other.faceMeshColors_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          faces_.AddEntriesFrom(input, _repeated_faces_codec);
          break;
        }
        case 18: {
          augmentations_.AddEntriesFrom(input, _repeated_augmentations_codec);
          break;
        }
        case 40: {
          Timestamp = input.ReadUInt64();
          break;
        }
        case 50:
        case 48: {
          contourThicknesses_.AddEntriesFrom(input, _repeated_contourThicknesses_codec);
          break;
        }
        case 58: {
          faceMeshColors_.AddEntriesFrom(input, _repeated_faceMeshColors_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          faces_.AddEntriesFrom(ref input, _repeated_faces_codec);
          break;
        }
        case 18: {
          augmentations_.AddEntriesFrom(ref input, _repeated_augmentations_codec);
          break;
        }
        case 40: {
          Timestamp = input.ReadUInt64();
          break;
        }
        case 50:
        case 48: {
          contourThicknesses_.AddEntriesFrom(ref input, _repeated_contourThicknesses_codec);
          break;
        }
        case 58: {
          faceMeshColors_.AddEntriesFrom(ref input, _repeated_faceMeshColors_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// A normalized version of above Landmark proto. All coordinates should be
/// within [0, 1].
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class NormalizedLandmark : pb::IMessage<NormalizedLandmark>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NormalizedLandmark> _parser = new pb::MessageParser<NormalizedLandmark>(() => new NormalizedLandmark());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NormalizedLandmark> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmark() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmark(NormalizedLandmark other) : this() {
    _hasBits0 = other._hasBits0;
    x_ = other.x_;
    y_ = other.y_;
    z_ = other.z_;
    visibility_ = other.visibility_;
    presence_ = other.presence_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmark Clone() {
    return new NormalizedLandmark(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private readonly static float XDefaultValue = 0F;

  private float x_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float X {
    get { if ((_hasBits0 & 1) != 0) { return x_; } else { return XDefaultValue; } }
    set {
      _hasBits0 |= 1;
      x_ = value;
    }
  }
  /// <summary>Gets whether the "x" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasX {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "x" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearX() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private readonly static float YDefaultValue = 0F;

  private float y_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Y {
    get { if ((_hasBits0 & 2) != 0) { return y_; } else { return YDefaultValue; } }
    set {
      _hasBits0 |= 2;
      y_ = value;
    }
  }
  /// <summary>Gets whether the "y" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasY {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "y" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearY() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "z" field.</summary>
  public const int ZFieldNumber = 3;
  private readonly static float ZDefaultValue = 0F;

  private float z_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Z {
    get { if ((_hasBits0 & 4) != 0) { return z_; } else { return ZDefaultValue; } }
    set {
      _hasBits0 |= 4;
      z_ = value;
    }
  }
  /// <summary>Gets whether the "z" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasZ {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "z" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearZ() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "visibility" field.</summary>
  public const int VisibilityFieldNumber = 4;
  private readonly static float VisibilityDefaultValue = 0F;

  private float visibility_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Visibility {
    get { if ((_hasBits0 & 8) != 0) { return visibility_; } else { return VisibilityDefaultValue; } }
    set {
      _hasBits0 |= 8;
      visibility_ = value;
    }
  }
  /// <summary>Gets whether the "visibility" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasVisibility {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "visibility" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearVisibility() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "presence" field.</summary>
  public const int PresenceFieldNumber = 5;
  private readonly static float PresenceDefaultValue = 0F;

  private float presence_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Presence {
    get { if ((_hasBits0 & 16) != 0) { return presence_; } else { return PresenceDefaultValue; } }
    set {
      _hasBits0 |= 16;
      presence_ = value;
    }
  }
  /// <summary>Gets whether the "presence" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPresence {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "presence" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPresence() {
    _hasBits0 &= ~16;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NormalizedLandmark);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NormalizedLandmark other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Visibility, other.Visibility)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Presence, other.Presence)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasX) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
    if (HasY) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
    if (HasZ) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
    if (HasVisibility) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Visibility);
    if (HasPresence) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Presence);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasX) {
      output.WriteRawTag(13);
      output.WriteFloat(X);
    }
    if (HasY) {
      output.WriteRawTag(21);
      output.WriteFloat(Y);
    }
    if (HasZ) {
      output.WriteRawTag(29);
      output.WriteFloat(Z);
    }
    if (HasVisibility) {
      output.WriteRawTag(37);
      output.WriteFloat(Visibility);
    }
    if (HasPresence) {
      output.WriteRawTag(45);
      output.WriteFloat(Presence);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasX) {
      output.WriteRawTag(13);
      output.WriteFloat(X);
    }
    if (HasY) {
      output.WriteRawTag(21);
      output.WriteFloat(Y);
    }
    if (HasZ) {
      output.WriteRawTag(29);
      output.WriteFloat(Z);
    }
    if (HasVisibility) {
      output.WriteRawTag(37);
      output.WriteFloat(Visibility);
    }
    if (HasPresence) {
      output.WriteRawTag(45);
      output.WriteFloat(Presence);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasX) {
      size += 1 + 4;
    }
    if (HasY) {
      size += 1 + 4;
    }
    if (HasZ) {
      size += 1 + 4;
    }
    if (HasVisibility) {
      size += 1 + 4;
    }
    if (HasPresence) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NormalizedLandmark other) {
    if (other == null) {
      return;
    }
    if (other.HasX) {
      X = other.X;
    }
    if (other.HasY) {
      Y = other.Y;
    }
    if (other.HasZ) {
      Z = other.Z;
    }
    if (other.HasVisibility) {
      Visibility = other.Visibility;
    }
    if (other.HasPresence) {
      Presence = other.Presence;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          X = input.ReadFloat();
          break;
        }
        case 21: {
          Y = input.ReadFloat();
          break;
        }
        case 29: {
          Z = input.ReadFloat();
          break;
        }
        case 37: {
          Visibility = input.ReadFloat();
          break;
        }
        case 45: {
          Presence = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 13: {
          X = input.ReadFloat();
          break;
        }
        case 21: {
          Y = input.ReadFloat();
          break;
        }
        case 29: {
          Z = input.ReadFloat();
          break;
        }
        case 37: {
          Visibility = input.ReadFloat();
          break;
        }
        case 45: {
          Presence = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Group of NormalizedLandmark protos.
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class NormalizedLandmarkList : pb::IMessage<NormalizedLandmarkList>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NormalizedLandmarkList> _parser = new pb::MessageParser<NormalizedLandmarkList>(() => new NormalizedLandmarkList());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NormalizedLandmarkList> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkList() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkList(NormalizedLandmarkList other) : this() {
    landmarks_ = other.landmarks_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkList Clone() {
    return new NormalizedLandmarkList(this);
  }

  /// <summary>Field number for the "landmarks" field.</summary>
  public const int LandmarksFieldNumber = 1;
  private static readonly pb::FieldCodec<global::NormalizedLandmark> _repeated_landmarks_codec
      = pb::FieldCodec.ForMessage(10, global::NormalizedLandmark.Parser);
  private readonly pbc::RepeatedField<global::NormalizedLandmark> landmarks_ = new pbc::RepeatedField<global::NormalizedLandmark>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::NormalizedLandmark> Landmarks {
    get { return landmarks_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NormalizedLandmarkList);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NormalizedLandmarkList other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!landmarks_.Equals(other.landmarks_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= landmarks_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    landmarks_.WriteTo(output, _repeated_landmarks_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    landmarks_.WriteTo(ref output, _repeated_landmarks_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += landmarks_.CalculateSize(_repeated_landmarks_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NormalizedLandmarkList other) {
    if (other == null) {
      return;
    }
    landmarks_.Add(other.landmarks_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          landmarks_.AddEntriesFrom(input, _repeated_landmarks_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          landmarks_.AddEntriesFrom(ref input, _repeated_landmarks_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Group of NormalizedLandmarkList protos.
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class NormalizedLandmarkListCollection : pb::IMessage<NormalizedLandmarkListCollection>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NormalizedLandmarkListCollection> _parser = new pb::MessageParser<NormalizedLandmarkListCollection>(() => new NormalizedLandmarkListCollection());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NormalizedLandmarkListCollection> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkListCollection() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkListCollection(NormalizedLandmarkListCollection other) : this() {
    landmarkLists_ = other.landmarkLists_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NormalizedLandmarkListCollection Clone() {
    return new NormalizedLandmarkListCollection(this);
  }

  /// <summary>Field number for the "landmark_lists" field.</summary>
  public const int LandmarkListsFieldNumber = 1;
  private static readonly pb::FieldCodec<global::NormalizedLandmarkList> _repeated_landmarkLists_codec
      = pb::FieldCodec.ForMessage(10, global::NormalizedLandmarkList.Parser);
  private readonly pbc::RepeatedField<global::NormalizedLandmarkList> landmarkLists_ = new pbc::RepeatedField<global::NormalizedLandmarkList>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::NormalizedLandmarkList> LandmarkLists {
    get { return landmarkLists_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NormalizedLandmarkListCollection);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NormalizedLandmarkListCollection other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!landmarkLists_.Equals(other.landmarkLists_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= landmarkLists_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    landmarkLists_.WriteTo(output, _repeated_landmarkLists_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    landmarkLists_.WriteTo(ref output, _repeated_landmarkLists_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += landmarkLists_.CalculateSize(_repeated_landmarkLists_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NormalizedLandmarkListCollection other) {
    if (other == null) {
      return;
    }
    landmarkLists_.Add(other.landmarkLists_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          landmarkLists_.AddEntriesFrom(input, _repeated_landmarkLists_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          landmarkLists_.AddEntriesFrom(ref input, _repeated_landmarkLists_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Could also add seperate color for lips?
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class FaceMeshColors : pb::IMessage<FaceMeshColors>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FaceMeshColors> _parser = new pb::MessageParser<FaceMeshColors>(() => new FaceMeshColors());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FaceMeshColors> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FaceMeshColors() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FaceMeshColors(FaceMeshColors other) : this() {
    faceMeshTesselationColor_ = other.faceMeshTesselationColor_ != null ? other.faceMeshTesselationColor_.Clone() : null;
    faceMeshContourColor_ = other.faceMeshContourColor_ != null ? other.faceMeshContourColor_.Clone() : null;
    faceMeshRightBrowColor_ = other.faceMeshRightBrowColor_ != null ? other.faceMeshRightBrowColor_.Clone() : null;
    faceMeshLeftBrowColor_ = other.faceMeshLeftBrowColor_ != null ? other.faceMeshLeftBrowColor_.Clone() : null;
    faceMeshRightEyeColor_ = other.faceMeshRightEyeColor_ != null ? other.faceMeshRightEyeColor_.Clone() : null;
    faceMeshLeftEyeColor_ = other.faceMeshLeftEyeColor_ != null ? other.faceMeshLeftEyeColor_.Clone() : null;
    faceMeshRightIrisColor_ = other.faceMeshRightIrisColor_ != null ? other.faceMeshRightIrisColor_.Clone() : null;
    faceMeshLeftIrisColor_ = other.faceMeshLeftIrisColor_ != null ? other.faceMeshLeftIrisColor_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FaceMeshColors Clone() {
    return new FaceMeshColors(this);
  }

  /// <summary>Field number for the "faceMesh_tesselation_color" field.</summary>
  public const int FaceMeshTesselationColorFieldNumber = 1;
  private global::EdgeColor faceMeshTesselationColor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EdgeColor FaceMeshTesselationColor {
    get { return faceMeshTesselationColor_; }
    set {
      faceMeshTesselationColor_ = value;
    }
  }

  /// <summary>Field number for the "faceMesh_contour_color" field.</summary>
  public const int FaceMeshContourColorFieldNumber = 2;
  private global::EdgeColor faceMeshContourColor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EdgeColor FaceMeshContourColor {
    get { return faceMeshContourColor_; }
    set {
      faceMeshContourColor_ = value;
    }
  }

  /// <summary>Field number for the "faceMesh_rightBrow_color" field.</summary>
  public const int FaceMeshRightBrowColorFieldNumber = 3;
  private global::EdgeColor faceMeshRightBrowColor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EdgeColor FaceMeshRightBrowColor {
    get { return faceMeshRightBrowColor_; }
    set {
      faceMeshRightBrowColor_ = value;
    }
  }

  /// <summary>Field number for the "faceMesh_leftBrow_color" field.</summary>
  public const int FaceMeshLeftBrowColorFieldNumber = 4;
  private global::EdgeColor faceMeshLeftBrowColor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EdgeColor FaceMeshLeftBrowColor {
    get { return faceMeshLeftBrowColor_; }
    set {
      faceMeshLeftBrowColor_ = value;
    }
  }

  /// <summary>Field number for the "faceMesh_rightEye_color" field.</summary>
  public const int FaceMeshRightEyeColorFieldNumber = 5;
  private global::EdgeColor faceMeshRightEyeColor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EdgeColor FaceMeshRightEyeColor {
    get { return faceMeshRightEyeColor_; }
    set {
      faceMeshRightEyeColor_ = value;
    }
  }

  /// <summary>Field number for the "faceMesh_leftEye_color" field.</summary>
  public const int FaceMeshLeftEyeColorFieldNumber = 6;
  private global::EdgeColor faceMeshLeftEyeColor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EdgeColor FaceMeshLeftEyeColor {
    get { return faceMeshLeftEyeColor_; }
    set {
      faceMeshLeftEyeColor_ = value;
    }
  }

  /// <summary>Field number for the "faceMesh_rightIris_color" field.</summary>
  public const int FaceMeshRightIrisColorFieldNumber = 7;
  private global::EdgeColor faceMeshRightIrisColor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EdgeColor FaceMeshRightIrisColor {
    get { return faceMeshRightIrisColor_; }
    set {
      faceMeshRightIrisColor_ = value;
    }
  }

  /// <summary>Field number for the "faceMesh_leftIris_color" field.</summary>
  public const int FaceMeshLeftIrisColorFieldNumber = 8;
  private global::EdgeColor faceMeshLeftIrisColor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EdgeColor FaceMeshLeftIrisColor {
    get { return faceMeshLeftIrisColor_; }
    set {
      faceMeshLeftIrisColor_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FaceMeshColors);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FaceMeshColors other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(FaceMeshTesselationColor, other.FaceMeshTesselationColor)) return false;
    if (!object.Equals(FaceMeshContourColor, other.FaceMeshContourColor)) return false;
    if (!object.Equals(FaceMeshRightBrowColor, other.FaceMeshRightBrowColor)) return false;
    if (!object.Equals(FaceMeshLeftBrowColor, other.FaceMeshLeftBrowColor)) return false;
    if (!object.Equals(FaceMeshRightEyeColor, other.FaceMeshRightEyeColor)) return false;
    if (!object.Equals(FaceMeshLeftEyeColor, other.FaceMeshLeftEyeColor)) return false;
    if (!object.Equals(FaceMeshRightIrisColor, other.FaceMeshRightIrisColor)) return false;
    if (!object.Equals(FaceMeshLeftIrisColor, other.FaceMeshLeftIrisColor)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (faceMeshTesselationColor_ != null) hash ^= FaceMeshTesselationColor.GetHashCode();
    if (faceMeshContourColor_ != null) hash ^= FaceMeshContourColor.GetHashCode();
    if (faceMeshRightBrowColor_ != null) hash ^= FaceMeshRightBrowColor.GetHashCode();
    if (faceMeshLeftBrowColor_ != null) hash ^= FaceMeshLeftBrowColor.GetHashCode();
    if (faceMeshRightEyeColor_ != null) hash ^= FaceMeshRightEyeColor.GetHashCode();
    if (faceMeshLeftEyeColor_ != null) hash ^= FaceMeshLeftEyeColor.GetHashCode();
    if (faceMeshRightIrisColor_ != null) hash ^= FaceMeshRightIrisColor.GetHashCode();
    if (faceMeshLeftIrisColor_ != null) hash ^= FaceMeshLeftIrisColor.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (faceMeshTesselationColor_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(FaceMeshTesselationColor);
    }
    if (faceMeshContourColor_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(FaceMeshContourColor);
    }
    if (faceMeshRightBrowColor_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(FaceMeshRightBrowColor);
    }
    if (faceMeshLeftBrowColor_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(FaceMeshLeftBrowColor);
    }
    if (faceMeshRightEyeColor_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(FaceMeshRightEyeColor);
    }
    if (faceMeshLeftEyeColor_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(FaceMeshLeftEyeColor);
    }
    if (faceMeshRightIrisColor_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(FaceMeshRightIrisColor);
    }
    if (faceMeshLeftIrisColor_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(FaceMeshLeftIrisColor);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (faceMeshTesselationColor_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(FaceMeshTesselationColor);
    }
    if (faceMeshContourColor_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(FaceMeshContourColor);
    }
    if (faceMeshRightBrowColor_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(FaceMeshRightBrowColor);
    }
    if (faceMeshLeftBrowColor_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(FaceMeshLeftBrowColor);
    }
    if (faceMeshRightEyeColor_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(FaceMeshRightEyeColor);
    }
    if (faceMeshLeftEyeColor_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(FaceMeshLeftEyeColor);
    }
    if (faceMeshRightIrisColor_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(FaceMeshRightIrisColor);
    }
    if (faceMeshLeftIrisColor_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(FaceMeshLeftIrisColor);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (faceMeshTesselationColor_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceMeshTesselationColor);
    }
    if (faceMeshContourColor_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceMeshContourColor);
    }
    if (faceMeshRightBrowColor_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceMeshRightBrowColor);
    }
    if (faceMeshLeftBrowColor_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceMeshLeftBrowColor);
    }
    if (faceMeshRightEyeColor_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceMeshRightEyeColor);
    }
    if (faceMeshLeftEyeColor_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceMeshLeftEyeColor);
    }
    if (faceMeshRightIrisColor_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceMeshRightIrisColor);
    }
    if (faceMeshLeftIrisColor_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceMeshLeftIrisColor);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FaceMeshColors other) {
    if (other == null) {
      return;
    }
    if (other.faceMeshTesselationColor_ != null) {
      if (faceMeshTesselationColor_ == null) {
        FaceMeshTesselationColor = new global::EdgeColor();
      }
      FaceMeshTesselationColor.MergeFrom(other.FaceMeshTesselationColor);
    }
    if (other.faceMeshContourColor_ != null) {
      if (faceMeshContourColor_ == null) {
        FaceMeshContourColor = new global::EdgeColor();
      }
      FaceMeshContourColor.MergeFrom(other.FaceMeshContourColor);
    }
    if (other.faceMeshRightBrowColor_ != null) {
      if (faceMeshRightBrowColor_ == null) {
        FaceMeshRightBrowColor = new global::EdgeColor();
      }
      FaceMeshRightBrowColor.MergeFrom(other.FaceMeshRightBrowColor);
    }
    if (other.faceMeshLeftBrowColor_ != null) {
      if (faceMeshLeftBrowColor_ == null) {
        FaceMeshLeftBrowColor = new global::EdgeColor();
      }
      FaceMeshLeftBrowColor.MergeFrom(other.FaceMeshLeftBrowColor);
    }
    if (other.faceMeshRightEyeColor_ != null) {
      if (faceMeshRightEyeColor_ == null) {
        FaceMeshRightEyeColor = new global::EdgeColor();
      }
      FaceMeshRightEyeColor.MergeFrom(other.FaceMeshRightEyeColor);
    }
    if (other.faceMeshLeftEyeColor_ != null) {
      if (faceMeshLeftEyeColor_ == null) {
        FaceMeshLeftEyeColor = new global::EdgeColor();
      }
      FaceMeshLeftEyeColor.MergeFrom(other.FaceMeshLeftEyeColor);
    }
    if (other.faceMeshRightIrisColor_ != null) {
      if (faceMeshRightIrisColor_ == null) {
        FaceMeshRightIrisColor = new global::EdgeColor();
      }
      FaceMeshRightIrisColor.MergeFrom(other.FaceMeshRightIrisColor);
    }
    if (other.faceMeshLeftIrisColor_ != null) {
      if (faceMeshLeftIrisColor_ == null) {
        FaceMeshLeftIrisColor = new global::EdgeColor();
      }
      FaceMeshLeftIrisColor.MergeFrom(other.FaceMeshLeftIrisColor);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (faceMeshTesselationColor_ == null) {
            FaceMeshTesselationColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshTesselationColor);
          break;
        }
        case 18: {
          if (faceMeshContourColor_ == null) {
            FaceMeshContourColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshContourColor);
          break;
        }
        case 26: {
          if (faceMeshRightBrowColor_ == null) {
            FaceMeshRightBrowColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshRightBrowColor);
          break;
        }
        case 34: {
          if (faceMeshLeftBrowColor_ == null) {
            FaceMeshLeftBrowColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshLeftBrowColor);
          break;
        }
        case 42: {
          if (faceMeshRightEyeColor_ == null) {
            FaceMeshRightEyeColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshRightEyeColor);
          break;
        }
        case 50: {
          if (faceMeshLeftEyeColor_ == null) {
            FaceMeshLeftEyeColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshLeftEyeColor);
          break;
        }
        case 58: {
          if (faceMeshRightIrisColor_ == null) {
            FaceMeshRightIrisColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshRightIrisColor);
          break;
        }
        case 66: {
          if (faceMeshLeftIrisColor_ == null) {
            FaceMeshLeftIrisColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshLeftIrisColor);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (faceMeshTesselationColor_ == null) {
            FaceMeshTesselationColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshTesselationColor);
          break;
        }
        case 18: {
          if (faceMeshContourColor_ == null) {
            FaceMeshContourColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshContourColor);
          break;
        }
        case 26: {
          if (faceMeshRightBrowColor_ == null) {
            FaceMeshRightBrowColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshRightBrowColor);
          break;
        }
        case 34: {
          if (faceMeshLeftBrowColor_ == null) {
            FaceMeshLeftBrowColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshLeftBrowColor);
          break;
        }
        case 42: {
          if (faceMeshRightEyeColor_ == null) {
            FaceMeshRightEyeColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshRightEyeColor);
          break;
        }
        case 50: {
          if (faceMeshLeftEyeColor_ == null) {
            FaceMeshLeftEyeColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshLeftEyeColor);
          break;
        }
        case 58: {
          if (faceMeshRightIrisColor_ == null) {
            FaceMeshRightIrisColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshRightIrisColor);
          break;
        }
        case 66: {
          if (faceMeshLeftIrisColor_ == null) {
            FaceMeshLeftIrisColor = new global::EdgeColor();
          }
          input.ReadMessage(FaceMeshLeftIrisColor);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// each color is a 4-tuple (r, g, b, a)
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EdgeColor : pb::IMessage<EdgeColor>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EdgeColor> _parser = new pb::MessageParser<EdgeColor>(() => new EdgeColor());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EdgeColor> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EdgeColor() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EdgeColor(EdgeColor other) : this() {
    r_ = other.r_;
    g_ = other.g_;
    b_ = other.b_;
    a_ = other.a_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EdgeColor Clone() {
    return new EdgeColor(this);
  }

  /// <summary>Field number for the "r" field.</summary>
  public const int RFieldNumber = 1;
  private int r_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int R {
    get { return r_; }
    set {
      r_ = value;
    }
  }

  /// <summary>Field number for the "g" field.</summary>
  public const int GFieldNumber = 2;
  private int g_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int G {
    get { return g_; }
    set {
      g_ = value;
    }
  }

  /// <summary>Field number for the "b" field.</summary>
  public const int BFieldNumber = 3;
  private int b_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int B {
    get { return b_; }
    set {
      b_ = value;
    }
  }

  /// <summary>Field number for the "a" field.</summary>
  public const int AFieldNumber = 4;
  private int a_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int A {
    get { return a_; }
    set {
      a_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EdgeColor);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EdgeColor other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (R != other.R) return false;
    if (G != other.G) return false;
    if (B != other.B) return false;
    if (A != other.A) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (R != 0) hash ^= R.GetHashCode();
    if (G != 0) hash ^= G.GetHashCode();
    if (B != 0) hash ^= B.GetHashCode();
    if (A != 0) hash ^= A.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (R != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(R);
    }
    if (G != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(G);
    }
    if (B != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(B);
    }
    if (A != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(A);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (R != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(R);
    }
    if (G != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(G);
    }
    if (B != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(B);
    }
    if (A != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(A);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (R != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(R);
    }
    if (G != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(G);
    }
    if (B != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(B);
    }
    if (A != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(A);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EdgeColor other) {
    if (other == null) {
      return;
    }
    if (other.R != 0) {
      R = other.R;
    }
    if (other.G != 0) {
      G = other.G;
    }
    if (other.B != 0) {
      B = other.B;
    }
    if (other.A != 0) {
      A = other.A;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          R = input.ReadInt32();
          break;
        }
        case 16: {
          G = input.ReadInt32();
          break;
        }
        case 24: {
          B = input.ReadInt32();
          break;
        }
        case 32: {
          A = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          R = input.ReadInt32();
          break;
        }
        case 16: {
          G = input.ReadInt32();
          break;
        }
        case 24: {
          B = input.ReadInt32();
          break;
        }
        case 32: {
          A = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Here if we want different augmentations for each part of face mesh
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class FaceAugmentations : pb::IMessage<FaceAugmentations>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FaceAugmentations> _parser = new pb::MessageParser<FaceAugmentations>(() => new FaceAugmentations());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FaceAugmentations> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecognitionDataFaceReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FaceAugmentations() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FaceAugmentations(FaceAugmentations other) : this() {
    faceMeshTesselationDesign_ = other.faceMeshTesselationDesign_;
    faceMeshContourDesign_ = other.faceMeshContourDesign_;
    faceMeshRightBrowDesign_ = other.faceMeshRightBrowDesign_;
    faceMeshLeftBrowDesign_ = other.faceMeshLeftBrowDesign_;
    faceMeshRightEyeDesign_ = other.faceMeshRightEyeDesign_;
    faceMeshLeftEyeDesign_ = other.faceMeshLeftEyeDesign_;
    faceMeshRightIrisDesign_ = other.faceMeshRightIrisDesign_;
    faceMeshLeftIrisDesign_ = other.faceMeshLeftIrisDesign_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FaceAugmentations Clone() {
    return new FaceAugmentations(this);
  }

  /// <summary>Field number for the "faceMesh_tesselation_design" field.</summary>
  public const int FaceMeshTesselationDesignFieldNumber = 1;
  private string faceMeshTesselationDesign_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FaceMeshTesselationDesign {
    get { return faceMeshTesselationDesign_; }
    set {
      faceMeshTesselationDesign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "faceMesh_contour_design" field.</summary>
  public const int FaceMeshContourDesignFieldNumber = 2;
  private string faceMeshContourDesign_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FaceMeshContourDesign {
    get { return faceMeshContourDesign_; }
    set {
      faceMeshContourDesign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "faceMesh_rightBrow_design" field.</summary>
  public const int FaceMeshRightBrowDesignFieldNumber = 3;
  private string faceMeshRightBrowDesign_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FaceMeshRightBrowDesign {
    get { return faceMeshRightBrowDesign_; }
    set {
      faceMeshRightBrowDesign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "faceMesh_leftBrow_design" field.</summary>
  public const int FaceMeshLeftBrowDesignFieldNumber = 4;
  private string faceMeshLeftBrowDesign_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FaceMeshLeftBrowDesign {
    get { return faceMeshLeftBrowDesign_; }
    set {
      faceMeshLeftBrowDesign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "faceMesh_rightEye_design" field.</summary>
  public const int FaceMeshRightEyeDesignFieldNumber = 5;
  private string faceMeshRightEyeDesign_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FaceMeshRightEyeDesign {
    get { return faceMeshRightEyeDesign_; }
    set {
      faceMeshRightEyeDesign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "faceMesh_leftEye_design" field.</summary>
  public const int FaceMeshLeftEyeDesignFieldNumber = 6;
  private string faceMeshLeftEyeDesign_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FaceMeshLeftEyeDesign {
    get { return faceMeshLeftEyeDesign_; }
    set {
      faceMeshLeftEyeDesign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "faceMesh_rightIris_design" field.</summary>
  public const int FaceMeshRightIrisDesignFieldNumber = 7;
  private string faceMeshRightIrisDesign_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FaceMeshRightIrisDesign {
    get { return faceMeshRightIrisDesign_; }
    set {
      faceMeshRightIrisDesign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "faceMesh_leftIris_design" field.</summary>
  public const int FaceMeshLeftIrisDesignFieldNumber = 8;
  private string faceMeshLeftIrisDesign_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FaceMeshLeftIrisDesign {
    get { return faceMeshLeftIrisDesign_; }
    set {
      faceMeshLeftIrisDesign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FaceAugmentations);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FaceAugmentations other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (FaceMeshTesselationDesign != other.FaceMeshTesselationDesign) return false;
    if (FaceMeshContourDesign != other.FaceMeshContourDesign) return false;
    if (FaceMeshRightBrowDesign != other.FaceMeshRightBrowDesign) return false;
    if (FaceMeshLeftBrowDesign != other.FaceMeshLeftBrowDesign) return false;
    if (FaceMeshRightEyeDesign != other.FaceMeshRightEyeDesign) return false;
    if (FaceMeshLeftEyeDesign != other.FaceMeshLeftEyeDesign) return false;
    if (FaceMeshRightIrisDesign != other.FaceMeshRightIrisDesign) return false;
    if (FaceMeshLeftIrisDesign != other.FaceMeshLeftIrisDesign) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (FaceMeshTesselationDesign.Length != 0) hash ^= FaceMeshTesselationDesign.GetHashCode();
    if (FaceMeshContourDesign.Length != 0) hash ^= FaceMeshContourDesign.GetHashCode();
    if (FaceMeshRightBrowDesign.Length != 0) hash ^= FaceMeshRightBrowDesign.GetHashCode();
    if (FaceMeshLeftBrowDesign.Length != 0) hash ^= FaceMeshLeftBrowDesign.GetHashCode();
    if (FaceMeshRightEyeDesign.Length != 0) hash ^= FaceMeshRightEyeDesign.GetHashCode();
    if (FaceMeshLeftEyeDesign.Length != 0) hash ^= FaceMeshLeftEyeDesign.GetHashCode();
    if (FaceMeshRightIrisDesign.Length != 0) hash ^= FaceMeshRightIrisDesign.GetHashCode();
    if (FaceMeshLeftIrisDesign.Length != 0) hash ^= FaceMeshLeftIrisDesign.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (FaceMeshTesselationDesign.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(FaceMeshTesselationDesign);
    }
    if (FaceMeshContourDesign.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(FaceMeshContourDesign);
    }
    if (FaceMeshRightBrowDesign.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(FaceMeshRightBrowDesign);
    }
    if (FaceMeshLeftBrowDesign.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(FaceMeshLeftBrowDesign);
    }
    if (FaceMeshRightEyeDesign.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(FaceMeshRightEyeDesign);
    }
    if (FaceMeshLeftEyeDesign.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(FaceMeshLeftEyeDesign);
    }
    if (FaceMeshRightIrisDesign.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(FaceMeshRightIrisDesign);
    }
    if (FaceMeshLeftIrisDesign.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(FaceMeshLeftIrisDesign);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (FaceMeshTesselationDesign.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(FaceMeshTesselationDesign);
    }
    if (FaceMeshContourDesign.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(FaceMeshContourDesign);
    }
    if (FaceMeshRightBrowDesign.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(FaceMeshRightBrowDesign);
    }
    if (FaceMeshLeftBrowDesign.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(FaceMeshLeftBrowDesign);
    }
    if (FaceMeshRightEyeDesign.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(FaceMeshRightEyeDesign);
    }
    if (FaceMeshLeftEyeDesign.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(FaceMeshLeftEyeDesign);
    }
    if (FaceMeshRightIrisDesign.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(FaceMeshRightIrisDesign);
    }
    if (FaceMeshLeftIrisDesign.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(FaceMeshLeftIrisDesign);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (FaceMeshTesselationDesign.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FaceMeshTesselationDesign);
    }
    if (FaceMeshContourDesign.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FaceMeshContourDesign);
    }
    if (FaceMeshRightBrowDesign.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FaceMeshRightBrowDesign);
    }
    if (FaceMeshLeftBrowDesign.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FaceMeshLeftBrowDesign);
    }
    if (FaceMeshRightEyeDesign.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FaceMeshRightEyeDesign);
    }
    if (FaceMeshLeftEyeDesign.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FaceMeshLeftEyeDesign);
    }
    if (FaceMeshRightIrisDesign.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FaceMeshRightIrisDesign);
    }
    if (FaceMeshLeftIrisDesign.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FaceMeshLeftIrisDesign);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FaceAugmentations other) {
    if (other == null) {
      return;
    }
    if (other.FaceMeshTesselationDesign.Length != 0) {
      FaceMeshTesselationDesign = other.FaceMeshTesselationDesign;
    }
    if (other.FaceMeshContourDesign.Length != 0) {
      FaceMeshContourDesign = other.FaceMeshContourDesign;
    }
    if (other.FaceMeshRightBrowDesign.Length != 0) {
      FaceMeshRightBrowDesign = other.FaceMeshRightBrowDesign;
    }
    if (other.FaceMeshLeftBrowDesign.Length != 0) {
      FaceMeshLeftBrowDesign = other.FaceMeshLeftBrowDesign;
    }
    if (other.FaceMeshRightEyeDesign.Length != 0) {
      FaceMeshRightEyeDesign = other.FaceMeshRightEyeDesign;
    }
    if (other.FaceMeshLeftEyeDesign.Length != 0) {
      FaceMeshLeftEyeDesign = other.FaceMeshLeftEyeDesign;
    }
    if (other.FaceMeshRightIrisDesign.Length != 0) {
      FaceMeshRightIrisDesign = other.FaceMeshRightIrisDesign;
    }
    if (other.FaceMeshLeftIrisDesign.Length != 0) {
      FaceMeshLeftIrisDesign = other.FaceMeshLeftIrisDesign;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          FaceMeshTesselationDesign = input.ReadString();
          break;
        }
        case 18: {
          FaceMeshContourDesign = input.ReadString();
          break;
        }
        case 26: {
          FaceMeshRightBrowDesign = input.ReadString();
          break;
        }
        case 34: {
          FaceMeshLeftBrowDesign = input.ReadString();
          break;
        }
        case 42: {
          FaceMeshRightEyeDesign = input.ReadString();
          break;
        }
        case 50: {
          FaceMeshLeftEyeDesign = input.ReadString();
          break;
        }
        case 58: {
          FaceMeshRightIrisDesign = input.ReadString();
          break;
        }
        case 66: {
          FaceMeshLeftIrisDesign = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          FaceMeshTesselationDesign = input.ReadString();
          break;
        }
        case 18: {
          FaceMeshContourDesign = input.ReadString();
          break;
        }
        case 26: {
          FaceMeshRightBrowDesign = input.ReadString();
          break;
        }
        case 34: {
          FaceMeshLeftBrowDesign = input.ReadString();
          break;
        }
        case 42: {
          FaceMeshRightEyeDesign = input.ReadString();
          break;
        }
        case 50: {
          FaceMeshLeftEyeDesign = input.ReadString();
          break;
        }
        case 58: {
          FaceMeshRightIrisDesign = input.ReadString();
          break;
        }
        case 66: {
          FaceMeshLeftIrisDesign = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
