# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognition_data.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16recognition_data.proto\"\xde\x02\n\x0fRecognitionData\x12#\n\rmask_contours\x18\x01 \x03(\x0b\x32\x0c.MaskContour\x12\x13\n\x05\x62oxes\x18\x02 \x03(\x0b\x32\x04.Box\x12\x0e\n\x06scores\x18\x03 \x03(\x02\x12\x13\n\x0b\x63lass_names\x18\x04 \x03(\t\x12)\n\x10geometry_centers\x18\x05 \x03(\x0b\x32\x0f.GeometryCenter\x12\x14\n\x05masks\x18\x06 \x03(\x0b\x32\x05.Mask\x12\x1a\n\x06\x63olors\x18\x07 \x03(\x0b\x32\n.MaskColor\x12\x15\n\raugmentations\x18\x08 \x03(\t\x12\x11\n\ttimestamp\x18\x0c \x01(\x04\x12&\n\x0elabel_property\x18\r \x01(\x0b\x32\x0e.LabelProperty\x12\x1b\n\x13\x63ontour_thicknesses\x18\x0e \x03(\x05\x12 \n\x0clabel_colors\x18\x0f \x03(\x0b\x32\n.MaskColor\"4\n\x0bMaskContour\x12%\n\x0einner_contours\x18\x01 \x03(\x0b\x32\r.ContourPoint\"$\n\x0c\x43ontourPoint\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"5\n\x03\x42ox\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02y1\x18\x02 \x01(\x05\x12\n\n\x02x2\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\"&\n\x0eGeometryCenter\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\'\n\x04Mask\x12\x1f\n\x0binner_masks\x18\x01 \x03(\x0b\x32\n.InnerMask\"\x19\n\tInnerMask\x12\x0c\n\x04mask\x18\x01 \x03(\x08\"7\n\tMaskColor\x12\t\n\x01r\x18\x01 \x01(\x05\x12\t\n\x01g\x18\x02 \x01(\x05\x12\t\n\x01\x62\x18\x03 \x01(\x05\x12\t\n\x01\x61\x18\x04 \x01(\x05\"6\n\rLabelProperty\x12\x11\n\ttext_size\x18\x02 \x01(\x05\x12\x12\n\nlabel_size\x18\x03 \x01(\x02\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"2\n\x04Quat\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognition_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOGNITIONDATA']._serialized_start=27
  _globals['_RECOGNITIONDATA']._serialized_end=377
  _globals['_MASKCONTOUR']._serialized_start=379
  _globals['_MASKCONTOUR']._serialized_end=431
  _globals['_CONTOURPOINT']._serialized_start=433
  _globals['_CONTOURPOINT']._serialized_end=469
  _globals['_BOX']._serialized_start=471
  _globals['_BOX']._serialized_end=524
  _globals['_GEOMETRYCENTER']._serialized_start=526
  _globals['_GEOMETRYCENTER']._serialized_end=564
  _globals['_MASK']._serialized_start=566
  _globals['_MASK']._serialized_end=605
  _globals['_INNERMASK']._serialized_start=607
  _globals['_INNERMASK']._serialized_end=632
  _globals['_MASKCOLOR']._serialized_start=634
  _globals['_MASKCOLOR']._serialized_end=689
  _globals['_LABELPROPERTY']._serialized_start=691
  _globals['_LABELPROPERTY']._serialized_end=745
  _globals['_VEC3']._serialized_start=747
  _globals['_VEC3']._serialized_end=786
  _globals['_QUAT']._serialized_start=788
  _globals['_QUAT']._serialized_end=838
# @@protoc_insertion_point(module_scope)
